### PR TITLE
Rewrite parser to use actual lexical analysis

### PR DESCRIPTION
**Pull request by IsaacKhor**
Sorry for disappearing for half a year; I had some stuff come up. Anyways, one of the items that has been on the todo list forever is writing a real parser: this is it. Featuring a real lexical grammar and and scanner that does real lexical analysis.

This is the first step in cleaning up the mess that is parsing right now.

Next steps:
- Multi-line support
- More lexical classes (maybe? will need to discuss the grammar first; I kind of just formalised what we already had anyways)
- Real error handling
- Comments (seems like there's some debate on about what we should do?)

### CODE REVIEW

**Comment by IsaacKhor** [comment]
I just saw #789, and for the most part, the lexemes seem to match up. I will write up my thoughts about a formal grammar for the exstring language once I have them there. Regardless, this doesn't really do anything to address the issue with parse tree generation; this only deals with the regular part of a compiler frontend.

**Comment by bovine3dom** [comment]
Have you seen https://github.com/ELLIOTTCABLE/excmd.js? It's probably worth collaborating on that.

**Comment by ELLIOTTCABLE** [comment]
Bahhah. Managed to duplicate some work, looks like! Oops.

Feel free to reach out and chat, I'm trucking along nicely. I'm in the IRC channel, as well as on Discord!

**Comment by bovine3dom** [comment]
Closing in favour of #1863. @ELLIOTTCABLE: please have a skim through this and see if there's anything worth integrating into yours.

**Pull request closed without merging**
