### PR TITLE
Add a new "auto" theme.

### PR DESCRIPTION
**Pull request by aaronrancsik**
This theme can adapt to system's light or dark theme variants. 
Solve: #3882

### CODE REVIEW

**Comment by aaronrancsik** [comment]
I'm just copied the whole "default" and "dark" theme  CSS into the corresponding media queries.. 
I bet there is more elegant solution because this way every time the "default" or "dark" theme is changing this theme is require an update.
Let me know how horrible my PR :D I will fix it.

**Comment by bovine3dom** [comment]
In theory you should be able to use `import` statements with relative URLs, conditionally loaded using media queries as shown here under examples: https://developer.mozilla.org/en-US/docs/Web/CSS/@import

I've never worked out how to do it but I'm not sure I have ever tried.

**Comment by aaronrancsik** [comment]
@bovine3dom All right I will give it a try thanks.

**Comment by bovine3dom** [comment]
Works great, thanks!

**Pull request merged**
