### PR TITLE
Fix completions for tabmove (#4602)

### PR DESCRIPTION
**Pull request by treapster**
Force default tabsort for tabmove.
Return trimmed prefix from splitOnPrefix for consistency.

I'm not sure how how safe is trimming splitOnPrefix::query so i didn't do it.

I was also astonished by updateOptions() and filter() having the same copypasted preamble in a ton of places. I'll try to clean it up this or next week, for now i just fixed what i broke, or at least i hope so:)

### CODE REVIEW

**Comment by bovine3dom** [comment]
> I was also astonished by updateOptions() and filter() having the same copypasted preamble in a ton of places. I'll try to clean it up this or next week, for now i just fixed what i broke, or at least i hope so:)

Yeah, the completions code is absolutely awful. I want to kill the whole thing and start from scratch (#3895).

I'm honestly a bit scared about refactoring it just a little because, at the moment, completions work _OK_ without too many race conditions. I think that is mostly because of luck than design ... unless we can simplify the code so much that we can reason that there will be no race conditions (which is what the plan is/was with #3895 ), I am not sure the benefits of having less copy-pasted code are worth the risk of re-introducing race conditions.

I would be happy to be persuaded otherwise.

**Comment by bovine3dom** [comment]
```
~/p/tridactyl (master|✚2) $ yarn run jscpd src/completions/
yarn run v1.22.19
$ /home/deck/projects/tridactyl/node_modules/.bin/jscpd src/completions/
Clone found (typescript):
 - src/completions/TabHistory.ts [34:14 - 49:8] (15 lines, 84 tokens)
   src/completions/Theme.ts [24:9 - 39:18]

Clone found (typescript):
 - src/completions/TabGroup.ts [80:14 - 98:13] (18 lines, 118 tokens)
   src/completions/Window.ts [54:8 - 72:21]

Clone found (typescript):
 - src/completions/TabAll.ts [166:5 - 181:12] (15 lines, 109 tokens)
   src/completions/Window.ts [57:5 - 72:21]

Clone found (typescript):
 - src/completions/Tab.ts [31:9 - 50:62] (19 lines, 206 tokens)
   src/completions/TabAll.ts [36:2 - 55:11]

Clone found (typescript):
 - src/completions/Sessions.ts [86:24 - 104:9] (18 lines, 116 tokens)
   src/completions/Window.ts [54:6 - 72:21]

Clone found (typescript):
 - src/completions/Rss.ts [44:9 - 62:3] (18 lines, 114 tokens)
   src/completions/Window.ts [54:6 - 72:6]

Clone found (typescript):
 - src/completions/History.ts [58:9 - 73:6] (15 lines, 103 tokens)
   src/completions/Settings.ts [38:9 - 53:39]

Clone found (typescript):
 - src/completions/Guiset.ts [27:7 - 41:5] (14 lines, 98 tokens)
   src/completions/Tab.ts [221:3 - 236:159]

Clone found (typescript):
 - src/completions/Goto.ts [29:7 - 60:19] (31 lines, 227 tokens)
   src/completions/Rss.ts [35:6 - 66:14]

Clone found (typescript):
 - src/completions/Excmd.ts [25:14 - 40:75] (15 lines, 84 tokens)
   src/completions/Theme.ts [24:9 - 39:18]

Clone found (typescript):
 - src/completions/Composite.ts [15:28 - 38:17] (23 lines, 164 tokens)
   src/completions/Excmd.ts [25:24 - 48:22]

Clone found (typescript):
 - src/completions/Composite.ts [68:9 - 76:10] (8 lines, 85 tokens)
   src/completions/Excmd.ts [61:9 - 68:6]

Clone found (typescript):
 - src/completions/Autocmd.ts [35:10 - 49:2] (14 lines, 111 tokens)
   src/completions/Rss.ts [35:6 - 49:2]

Clone found (typescript):
 - src/completions/Apropos.ts [6:2 - 14:30] (8 lines, 81 tokens)
   src/completions/Help.ts [6:2 - 14:30]

Clone found (typescript):
 - src/completions/Apropos.ts [24:10 - 65:2] (41 lines, 318 tokens)
   src/completions/Help.ts [24:7 - 64:6]

Clone found (typescript):
 - src/completions/Apropos.ts [133:24 - 167:2] (34 lines, 267 tokens)
   src/completions/Help.ts [116:21 - 150:2]

┌────────────┬────────────────┬─────────────┬──────────────┬──────────────┬──────────────────┬───────────────────┐
│ Format     │ Files analyzed │ Total lines │ Total tokens │ Clones found │ Duplicated lines │ Duplicated tokens │
├────────────┼────────────────┼─────────────┼──────────────┼──────────────┼──────────────────┼───────────────────┤
│ typescript │ 25             │ 3092        │ 24570        │ 16           │ 306 (9.9%)       │ 2285 (9.3%)       │
├────────────┼────────────────┼─────────────┼──────────────┼──────────────┼──────────────────┼───────────────────┤
│ Total:     │ 25             │ 3092        │ 24570        │ 16           │ 306 (9.9%)       │ 2285 (9.3%)       │
└────────────┴────────────────┴─────────────┴──────────────┴──────────────┴──────────────────┴───────────────────┘
Found 16 clones.
Detection time:: 500.352ms
Done in 1.29s.
```

**Comment by treapster** [comment]
> I'm honestly a bit scared about refactoring it just a little because, at the moment, completions work _OK_ without too many race conditions.  I think that is mostly because of luck than design ... unless we can simplify the code so much that we can reason that there will be no race conditions (which is what the plan is/was with #3895 ), I am not sure the benefits of having less copy-pasted code are worth the risk of re-introducing race conditions.

IMO moving copypasted code in one place and changing a couple of function signatures is not too dangerous, plus it will make code simpler to maintain and reason about. Rewrites are cool, but firstly they 're even more probable to introduce bugs than small patches, secondly they require a lot of concentrated time and effort which makes them really hard to finish, and most importantly, the goals of rewrites are almost always achievable by incremental changes. Thus, doing a cleanup is a good start. 

If you have formed some vision of the new API, how about creating an issue which will describe it and lay out steps needed to implement it(if there isn't already)?

**Comment by bovine3dom** [comment]
I'll make a meta-issue - #2865 is the closest we have at the moment

**Pull request merged**
