### PR TITLE
Update config.ts: stop loading

### PR DESCRIPTION
**Pull request by FrankEular**
I added the command ":stop" and an nmap <C-c> to this command (as in vimperator and pentadactyl).

### CODE REVIEW

**Comment by bovine3dom** [comment]
Thanks.

Why did you remove the `x` bind? Is that not what it was bound to?

**Comment by FrankEular** [comment]
just because it seems to me that vimperator and pentadactyl don't bind x to :stop by default (if their help page is genuine).

**Comment by bovine3dom** [comment]
I'd rather it was bound to `x` by default. I'm sure _someone_ uses that as a bind for stop.

My reasoning is that Ctrl-C is widely used to copy text and this would break that (probably - or at least introduce weird side effects to copying). I'd be happier to bind it to Ctrl-C once we have a visual mode.

You're obviously welcome to bind it to whatever you want in your own configuration : )

**Comment by bovine3dom** [comment]
I've changed the bind to `x` and merged. Thanks!

**Pull request merged**
