### PR TITLE
TSLint: re-enable curly rule

### PR DESCRIPTION
**Pull request by glacambre**

### CODE REVIEW

**Comment by bovine3dom** [comment]
I'm less convinced about this than the others. Do you know why it's recommended?

**Comment by glacambre** [comment]
I think it's because it's easier to mistake a piece of code as being (or not being) part of an if statement if the if statement doesn't have curly braces. It also makes things slightly less ambiguous for the compiler. For example, Typescript thinks things like this:
```ts
if (cond)
    return x
(obj as any).doSomething()
```
mean that we want to return `x(obj as any).doSomething()` while
```ts
if (cond) {
    return x
}
(obj as any).doSomething()
```
is unambiguous.

While I do prefer enforcing curly braces everywhere, I don't feel strongly about it, so I won't mind if this is not merged :).

**Comment by cmcaine** [comment]
I prefer not having to type my curly braces when they're not necessary.

If the computer will automatically insert them without asking me about it,
then I don't care.

The case with the brackets on a new line hardly ever happens (and current
style is to put a semicolon on the same line before the bracket).

**Comment by glacambre** [comment]
>If the computer will automatically insert them without asking me about it, then I don't care.

`tslint --fix` can automatically do that (in fact it's what I used in order to create this commit).

**Comment by cmcaine** [comment]
I still have a slight preference for rejecting this. Up to you, Olie

**Comment by glacambre** [comment]
This became unmergeable so let's close it.

**Pull request closed without merging**
