### PR TITLE
Base16 Themes

### PR DESCRIPTION
**Pull request by bezmi**
I decided to modify the Shydactyl theme with base16 colours. I thought I'd incorporate all of the current base16 themes and start a pull request in case anybody else would like to use them too. 

LICENSE is in there because the author of base16 has licensed it under MIT, so I just included it as that is part of the terms, I'm new to contributing so I have no idea if this is necessary.

I might also modify the classic themes to base16 colours if people are interested.

### CODE REVIEW

**Comment by bovine3dom** [comment]
There seems to be a lot of redundancy between these. I'm reluctant to merge this as it is - I don't want to have to change 76 files every time we change something theme related.

Perhaps some concept of a palette that could be applied on top of a theme would make sense? Then we would get dark versions of all the themes for free.

**Comment by bezmi** [comment]
you just need to run `set theme 3024` I wasn't sure when that pull request was going to be merged, but it will work much better that way and also allow me to publish these to the main base16 repo. 

The only things that change between files are the definitions of the 16 colours themselves. Is there some way for me to have the theme pallettes defined in separate files and then include them as variables to the main file that has the actual layout in it? Not sure how I could go about doing that, this is my first time playing around with css and web-extensions in general.

**Comment by bovine3dom** [comment]
I'm not sure either, @bezmi. My suggestion which I thought about for all of 20 seconds was to have a `set palette` ex command in Tridactyl that set the variables after the theme.

It might be better to just allow people to apply as many themes as they like on top of each other.

**Comment by cmcaine** [comment]
CSS files can include one another with @import so there's definitely no
need to duplicate the files in their entireties. Introducing a notion of
palettes might be better, but it seems like just introducing tridactyl
specific styling syntax. I think we should just expose the CSS if users
want to customise it.

**Comment by bezmi** [comment]
I believe that is the right way to go here, I will close this pull request for now.

**Comment by glacambre** [comment]
@bezmi #865 has been merged, are your themes available somewhere on github in order for us to mention them on our readme/soon-to-be wiki?

**Comment by pjvds** [comment]
> @bezmi #865 has been merged, are your themes available somewhere on github in order for us to mention them on our readme/soon-to-be wiki?

Would love to have a single overview of the available themes ❤️

**Comment by bezmi** [comment]
I deleted the original pull request repo, but I will set up a base16-tridactyl repo when I have time - not for several weeks.

**Pull request closed without merging**
