### PR TITLE
Move circleci CI to github

### PR DESCRIPTION
**Pull request by glacambre**

### CODE REVIEW

**Comment by bovine3dom** [comment]
Thanks for this! I'd like lint, mozilla and unit to be separated out into different jobs if that's ok - they tend to fail at different times.

If you don't have time to look at it I'll do it eventually

**Comment by glacambre** [comment]
>I'd like lint, mozilla and unit to be separated out into different jobs if that's ok

IMO it doesn't make much sense - half of the time spent on each separate job is from downloading the tridactyl repo and running `yarn install` - this results in [burning three minutes of CI](https://github.com/tridactyl/tridactyl/actions/runs/6218772216/usage?pr=4769) where running each step in the same job would result in only using [a minute and 45 seconds of CI](https://github.com/tridactyl/tridactyl/actions/runs/6218643608/usage?pr=4769).

I'm under the impression that the reason you want to have multiple jobs is to have each lint step be run regardless of whether the others failed, it's possible to tweak the workflow file [like this](https://github.com/tridactyl/tridactyl/actions/runs/6218643608/workflow?pr=4769) to achieve that.

If you prefer to keep multiple jobs feel free to merge this PR, if you prefer to use steps instead just let me know and I'll change the PR to the example above :)

**Comment by bovine3dom** [comment]
I just want a nice big tick/cross next to each step so that I can see easily why it failed

It would be nice to use the minimum amount of computer time to do so :)

**Comment by glacambre** [comment]
>I just want a nice big tick/cross next to each step so that I can see easily why it failed

The this PR in its current state is optimal I think :).

>It would be nice to use the minimum amount of computer time to do so :)

We could try to only perform `yarn install` once and then upload the current working dir to github artifacts and download then in subsequent jobs, but I doubt we'll gain anything from it: I'm convinced `yarn install` is bottlenecked by network bandwitdh already and downloading/uploading the same amount of data from somewhere else would not change anything.

**Pull request merged**
