### PR TITLE
BrowserBg breaks in very subtle ways 

### PR DESCRIPTION
**Pull request by glacambre**
This isn't an actual pull request but I think being able to comment on the code itself might be useful.
The bug I'm experiencing is that BrowserBg returns something that looks like an Array but isn't actually an Array.

In order to reproduce it pull my code, compile it, load it in Firefox, open "example.org", open the content script console and type `:bmarks `. The message "Bookmarks is an array and bookmarks[0] is not an array and bookmarks[0][0] is not an array" will be printed in the console. Below it, two arrays and an object are printed.

Now, open the newtab page and repeat this sequence of actions. The message "Bookmarks is an array and bookmarks[0] is an array and bookmarks[0][0] is not an array" will be printed in the console. Notice the difference between example.org and newtab: bookmarks[0] is an array in newtab (which is executing with the same privileges as a background script, so bypassing browserBg I think) and it isn't on example.org.

I really don't understand what's happening here, why aren't arrays returned by browserBg while in the content script actual arrays?

### CODE REVIEW

**Comment by bovine3dom** [comment]
I don't see any difference between the objects produced by

```js
tri.browserBg.bookmarks.search({}).then(x=>x.map(y=>tri.browserBg.bookmarks.getSubTree(y.id).then(console.log)))
```

on the new tab page web console

and 

```js
:js tri.browserBg.bookmarks.search({}).then(x=>x.map(y=>tri.browserBg.bookmarks.getSubTree(y.id).then(console.log)))
```

on any normal page, with results logged in the web console.

I'll see if the PR can let me reproduce your issue.

**Comment by cmcaine** [comment]
I suspect this is due to how Firefox serialises objects when passing them via messaging. Might be worth a bug on Firefox if we can isolate it. Maybe also worth retrying with Array.isArray rather than instanceof.

The browser proxy code is a total of 20 lines or so and I'm fairly confident that it's not mutating any of the arguments given.

**Comment by bovine3dom** [comment]
`js tri.browserBg.bookmarks.search({}).then(x=>x.map(y=>tri.browserBg.bookmarks.getSubTree(y.id).then(z=>console.log(Array.isArray(z)))))` gives me all trues on normal pages and the new tab page.

**Comment by glacambre** [comment]
Closing as we'll probably never know what is happening.

**Pull request closed without merging**
