### PR TITLE
Add functions to move cursor up and down in text areas

### LINKED ISSUE #4831: Add functions to move cursor up and down
Hi, Emacs user here:)!
Can you add functions `next_line` and `previous_line` to move cursor up and down inside text fields? I'm totally unprofessional in browser-related stuff, so can't do it myself (though I tried)

### PR DESCRIPTION
**Pull request by jumper047**
This PR fixes #4831

### CODE REVIEW

**Comment by bovine3dom** [comment]
Thanks for this! Can you give me an example of a website where it works? I know text areas are a bit temperamental

For me I get "t is not defined" with:

1. `:bind --mode=insert <C-i> text.next_line`
2. `:open https://0.0g.gg/`
3. (type some stuff in the box, make some newlines)
4. `<C-i>` `# controller in excmd: ReferenceError: t is not defined`

**Comment by bovine3dom** [comment]
Works great, thanks!

**Comment by jumper047** [comment]
Hi again, I have an issue and not sure is it my fault or something really goes wrong. I installed beta version of the extension from this link - https://tridactyl.cmcaine.co.uk/betas/tridactyl-latest.xpi . Unfurtunately, I got an error like `Not an excmd: text.next_line`. I tried to uninstall extension from store, nothing changed. Then I grepped through code in .xpi archive, and seems like there is no `next_line` function in it. Is it something wrong with xpi, link, or steps I made?

**Comment by bovine3dom** [comment]
Sorry @jumper047, I just saw your message. Do you still get the same behaviour? `next_line` has been out in Tridactyl stable since `1.23.0pre6882`

**Pull request merged**
