### PR TITLE
Avoid time paradox when undo tabs

### PR DESCRIPTION
**Pull request by fluem**
Issue #3302. Sorting the recently closed tabs takes care of @glacambre's case, but there are still cases with three tabs or multiple time jumps where the order is wrong. Have to look at this again.

### CODE REVIEW

**Review by glacambre — COMMENTED** [review]
LGTM, thanks for fixing this! :)

**Comment by bovine3dom** [comment]
Happy to merge this now and you can think about the edge cases some other time, if you want. Either way is OK with me

**Comment by fluem** [comment]
I sorted the wrong way round and it screws up the normal timeline. Have to figure it out a different way. Sorry, no ready to merge yet.

**Comment by fluem** [comment]
Removed the incorrect sorting, but kept the nicer time formatting for negative times.

**Pull request merged**
